### ISSUE TITLE
Sugestie engine

### ISSUE THREAD

**Issue by alin-rautoiu** [codingNonGuru/JocDesprePrecariat#2]
Am putea folosi, din motive ideologice, [Godot](https://godotengine.org/)?

**Comment by codingNonGuru** [comment]
Văd că are varianta de Linux, ceea ce îmi convine. Per total arată interesant. Însă pentru moment prefer Unity, deoarece simt că îmi este dificil să învăț un nou engine/limbaj.

Tu ce crezi că îl recomandă?

**Comment by alin-rautoiu** [comment]
Ideologic în primul rînd, că-i un proiect open-source făcut de niște oameni care au câteva instincte ușor progresiste (de exemplu [codul de etică](https://godotengine.org/code-of-conduct)) și sunt împotriva comodificării.

Apoi, mi se pare că Unity s-a grăbit în ultimii ani să ajungă la paritate de feature-uri cu multe alte motoare destul de diferite încît totul se simte half-baked și neînchegat. Viteza cu care ajung să pună pe piață feature-uri îl mențin într-o stare de permanent beta.

Pe de altă parte recunosc că-i mai mult o chestie de feeling, iar chiar și aici progresează lucrurile încetul cu încetul.

Cred totuși că merită stat cu ochii pe el, chiar dacă nu-l folosești aici.

**Comment by alin-rautoiu** [comment]
Așa, informativ, un video care compară în linii mari Godot cu Unity și Unreal
https://www.youtube.com/watch?v=l7BrpcboJno
