### ISSUE TITLE
Recrutare graficianx

### ISSUE THREAD

**Issue by codingNonGuru** [codingNonGuru/JocDesprePrecariat#4]
@alin-rautoiu ziceai că știi pe cineva interesat să se ocupe de partea grafică.

**Comment by alin-rautoiu** [comment]
Da https://www.instagram.com/luciaspinoiu/?hl=en.

**Comment by alin-rautoiu** [comment]
LuciSp e userul ei.

**Comment by codingNonGuru** [comment]
Gata, am adăugat-o.
